def gpiochip_open(chip: int) -> int: ...
def gpiochip_close(handle: int) -> None: ...
def gpio_claim_output(handle: int, gpio: int, level: int = 0, flags: int = 0) -> None: ...
def gpio_write(handle: int, gpio: int, level: int) -> None: ...
def gpio_free(handle: int, gpio: int) -> None: ...
